"""
Base agent class for the healthcare AI agent system.

All specialised agents (Symptom, Diagnosis, Triage, Precaution, Summary)
inherit from ``BaseAgent`` which provides:
- Structured system prompt management
- Claude API integration with JSON output
- Retry / fallback logic (delegated to claude_client)
- Logging and metrics hooks
- Medical disclaimer injection
"""

from abc import ABC, abstractmethod
from typing import Any

from app.core.claude_client import call_claude, call_claude_json
from app.core.logging import get_logger

logger = get_logger(__name__)

# Universal medical disclaimer appended to every agent output
MEDICAL_DISCLAIMER = (
    "⚠️ DISCLAIMER: This information is generated by an AI system and is for "
    "informational purposes only. It is NOT a substitute for professional medical "
    "advice, diagnosis, or treatment. Always seek the advice of a qualified "
    "healthcare provider with any questions regarding a medical condition. "
    "If you think you may have a medical emergency, call your doctor or "
    "emergency services immediately."
)


class BaseAgent(ABC):
    """Abstract base class for all healthcare AI agents.

    Subclasses must implement:
    - ``system_prompt``: The agent's role and instructions.
    - ``process()``: The main processing logic.

    Attributes:
        name: Human-readable agent name for logging.
        temperature: Claude sampling temperature (lower = more deterministic).
        json_mode: Whether to request structured JSON output from Claude.
    """

    name: str = "BaseAgent"
    temperature: float = 0.2
    json_mode: bool = True

    @property
    @abstractmethod
    def system_prompt(self) -> str:
        """Return the system prompt that defines this agent's role and behaviour."""
        ...

    @abstractmethod
    async def process(self, input_data: dict[str, Any]) -> dict[str, Any]:
        """Execute the agent's primary task.

        Args:
            input_data: Agent-specific input dictionary.

        Returns:
            Agent-specific output dictionary with results.
        """
        ...

    async def _call_llm(self, user_message: str) -> dict[str, Any]:
        """Call Claude with this agent's system prompt and return parsed JSON.

        Args:
            user_message: The formatted prompt for the user turn.

        Returns:
            Parsed JSON response dictionary.
        """
        logger.info("[%s] Processing request (json_mode=%s)", self.name, self.json_mode)

        if self.json_mode:
            result = await call_claude_json(
                self.system_prompt,
                user_message,
                temperature=self.temperature,
            )
        else:
            raw = await call_claude(
                self.system_prompt,
                user_message,
                temperature=self.temperature,
            )
            result = {"response": raw}

        if result.get("error"):
            logger.warning("[%s] LLM returned error: %s", self.name, result["error"])

        return result

    async def _call_llm_text(self, user_message: str) -> str:
        """Call Claude and return raw text response.

        Args:
            user_message: The formatted prompt.

        Returns:
            Raw text response string.
        """
        return await call_claude(
            self.system_prompt,
            user_message,
            temperature=self.temperature,
        )

    def _add_disclaimer(self, result: dict[str, Any]) -> dict[str, Any]:
        """Inject the medical disclaimer into the result dict.

        Args:
            result: The agent's output dictionary.

        Returns:
            The same dictionary with ``disclaimer`` key added.
        """
        result["disclaimer"] = MEDICAL_DISCLAIMER
        return result

    def _format_symptoms_for_prompt(self, symptoms: list[str]) -> str:
        """Format a list of symptoms into a readable prompt section.

        Args:
            symptoms: List of symptom names.

        Returns:
            Formatted multi-line string.
        """
        if not symptoms:
            return "No symptoms provided."
        return "\n".join(f"- {s.replace('_', ' ').title()}" for s in symptoms)
